using Microsoft.EntityFrameworkCore;

namespace SeaWay.Data;

public static class DatabaseInitializer
{
    public static async Task InitializeAsync(SeaWayDbContext dbContext)
    {
        var sql = """
            CREATE TABLE IF NOT EXISTS tbl_m_role (
                role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                role_code varchar(80) NOT NULL UNIQUE,
                role_name varchar(120) NOT NULL,
                description text NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamp without time zone NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS tbl_m_user_login (
                user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username varchar(80) NOT NULL UNIQUE,
                password_text varchar(120) NOT NULL,
                full_name varchar(150) NOT NULL,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamp without time zone NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS tbl_r_user_role (
                user_role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NOT NULL REFERENCES tbl_m_user_login(user_id),
                role_id integer NOT NULL REFERENCES tbl_m_role(role_id),
                is_default boolean NOT NULL DEFAULT true,
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamp without time zone NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS tbl_t_login_audit (
                login_audit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id integer NULL,
                username varchar(80) NOT NULL,
                role_name varchar(120) NULL,
                ip_address varchar(80) NULL,
                user_agent text NULL,
                login_at timestamp without time zone NOT NULL DEFAULT now(),
                login_status varchar(30) NOT NULL
            );

            CREATE TABLE IF NOT EXISTS tbl_m_unit (
                unit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                unit_code varchar(80) NOT NULL UNIQUE,
                unit_name varchar(150) NOT NULL,
                device_idno varchar(40) NOT NULL UNIQUE,
                session_token varchar(120) NOT NULL,
                gps_status_url text NULL,
                camera_url text NULL,
                unit_image_url text NULL,
                icon_key varchar(40) NOT NULL DEFAULT 'ship',
                unit_type varchar(80) NULL,
                unit_detail text NULL,
                is_active boolean NOT NULL DEFAULT true,
                is_default boolean NOT NULL DEFAULT false,
                created_at timestamp without time zone NOT NULL DEFAULT now(),
                updated_at timestamp without time zone NULL
            );

            ALTER TABLE tbl_m_unit
                ADD COLUMN IF NOT EXISTS unit_image_url text NULL;

            INSERT INTO tbl_m_role (role_code, role_name, description, is_active)
            SELECT 'fleet_admin', 'Fleet Admin', 'Akses penuh ke konfigurasi dan monitoring.', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_role WHERE role_code = 'fleet_admin');

            INSERT INTO tbl_m_role (role_code, role_name, description, is_active)
            SELECT 'fleet_operator', 'Fleet Operator', 'Monitoring harian armada dan acknowledgement alert.', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_role WHERE role_code = 'fleet_operator');

            INSERT INTO tbl_m_role (role_code, role_name, description, is_active)
            SELECT 'port_captain', 'Port Captain', 'Approval deviasi dan audit pergerakan area pelabuhan.', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_role WHERE role_code = 'port_captain');

            INSERT INTO tbl_m_role (role_code, role_name, description, is_active)
            SELECT 'viewer', 'Viewer', 'Read only monitoring.', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_role WHERE role_code = 'viewer');

            INSERT INTO tbl_m_user_login (username, password_text, full_name, is_active)
            SELECT 'admin', 'admin123', 'SeaWay Administrator', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_user_login WHERE username = 'admin');

            INSERT INTO tbl_m_user_login (username, password_text, full_name, is_active)
            SELECT 'operator', 'operator123', 'SeaWay Fleet Operator', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_user_login WHERE username = 'operator');

            INSERT INTO tbl_m_user_login (username, password_text, full_name, is_active)
            SELECT 'captain', 'captain123', 'SeaWay Port Captain', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_user_login WHERE username = 'captain');

            INSERT INTO tbl_m_user_login (username, password_text, full_name, is_active)
            SELECT 'viewer', 'viewer123', 'SeaWay Read Only', true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_user_login WHERE username = 'viewer');

            INSERT INTO tbl_r_user_role (user_id, role_id, is_default, is_active)
            SELECT u.user_id, r.role_id, true, true
            FROM tbl_m_user_login u
            JOIN tbl_m_role r ON r.role_code = 'fleet_admin'
            WHERE u.username = 'admin'
              AND NOT EXISTS (
                  SELECT 1
                  FROM tbl_r_user_role ur
                  WHERE ur.user_id = u.user_id AND ur.role_id = r.role_id
              );

            INSERT INTO tbl_r_user_role (user_id, role_id, is_default, is_active)
            SELECT u.user_id, r.role_id, true, true
            FROM tbl_m_user_login u
            JOIN tbl_m_role r ON r.role_code = 'fleet_operator'
            WHERE u.username = 'operator'
              AND NOT EXISTS (
                  SELECT 1
                  FROM tbl_r_user_role ur
                  WHERE ur.user_id = u.user_id AND ur.role_id = r.role_id
              );

            INSERT INTO tbl_r_user_role (user_id, role_id, is_default, is_active)
            SELECT u.user_id, r.role_id, true, true
            FROM tbl_m_user_login u
            JOIN tbl_m_role r ON r.role_code = 'port_captain'
            WHERE u.username = 'captain'
              AND NOT EXISTS (
                  SELECT 1
                  FROM tbl_r_user_role ur
                  WHERE ur.user_id = u.user_id AND ur.role_id = r.role_id
              );

            INSERT INTO tbl_r_user_role (user_id, role_id, is_default, is_active)
            SELECT u.user_id, r.role_id, true, true
            FROM tbl_m_user_login u
            JOIN tbl_m_role r ON r.role_code = 'viewer'
            WHERE u.username = 'viewer'
              AND NOT EXISTS (
                  SELECT 1
                  FROM tbl_r_user_role ur
                  WHERE ur.user_id = u.user_id AND ur.role_id = r.role_id
              );

            INSERT INTO tbl_m_unit (
                unit_code, unit_name, device_idno, session_token, gps_status_url, camera_url, unit_image_url, icon_key, unit_type, unit_detail, is_active, is_default
            )
            SELECT
                'RD4003',
                'RD4003 - SeaWay Live Unit',
                '221083241090',
                '7725f0b6e9404a5d86bb6ccab539db9e',
                'http://103.245.39.218:8080/StandardApiAction_getDeviceStatus.action',
                '/808gps/open/player/video.html?lang=en&devIdno=353075846831&account=LenzguardUnggul&password=UDULENZGUARD123',
                '/image/ship.png',
                'ship',
                'Merchant Vessel',
                'Live GPS/AIS unit untuk monitoring operasional SeaWay.',
                true,
                true
            WHERE NOT EXISTS (SELECT 1 FROM tbl_m_unit WHERE device_idno = '221083241090');
            """;

        await dbContext.Database.ExecuteSqlRawAsync(sql);
    }
}
